### ISSUE TITLE
Fix viewport issue on small screens

### ISSUE THREAD

**Issue by cody-hoffman** [TractorZoom/component-library#6]
When running storybook and using phones to test components the viewport is cutting off the components and making them look non-responsive:
<img width="527" alt="Screen Shot 2020-07-08 at 10 14 52 AM" src="https://user-images.githubusercontent.com/58948825/86938938-9d39d900-c106-11ea-9eea-b159e181ca0d.png">

**Comment by twebber90** [comment]
moved issue to Jira https://tractorzoom.atlassian.net/browse/TZ-3053?atlOrigin=eyJpIjoiZWMxN2MwOTc3MjIzNDZjNWE4MWRiZmI3N2U5NmNjNzkiLCJwIjoiaiJ9
